### PR TITLE
Skip writing parquet output files if there were no validation errors

### PR DESCRIPTION
**Pull request by atvaccaro**
See https://github.com/cal-itp/data-infra/issues/1180 for more context.

This PR fixes the actual underlying cause, but I've already moved the offending files currently in GCS.

### CODE REVIEW

**Review by lauriemerrell — COMMENTED** [review]
Is there any chance that we want to write a file that's called like `empty_service_alerts` or something just to remove any ambiguity about whether the validator actually ran on the feed? I'm just wondering about a world where we can't tell the difference between "validator didn't run" and "no validations found". Or, as you mentioned in another place, can we make sure that the columns will be written but empty?

**Comment by atvaccaro** [comment]
> Is there any chance that we want to write a file that's called like `empty_service_alerts` or something just to remove any ambiguity about whether the validator actually ran on the feed? I'm just wondering about a world where we can't tell the difference between "validator didn't run" and "no validations found". Or, as you mentioned in another place, can we make sure that the columns will be written but empty?

Eh I'm hesitant to add dummy files. I think the columns idea is interesting, but right now I'm trying to minimize changes since I want to move to ndjson anyways. Is that fair?

**Comment by lauriemerrell** [comment]
Ok, I'm fine with that as long as we prioritize https://github.com/cal-itp/data-infra/issues/1345 soon

**Review by lauriemerrell — APPROVED** [review]

**Comment by holly-g** [comment]
Fixes https://github.com/cal-itp/data-infra/issues/1180

**Pull request merged**
